version: "3"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./.devcontainer/docker/Dockerfile
    tty: true
    command: uwsgi --ini /code/nginx/uwsgi.ini
    volumes:
      - .:/code:cached
      - ./static:/static
    expose:
      - "8001"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: djangodb123
      POSTGRES_USER: djangodb
      POSTGRES_DB: blog
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  proxy:
    image: nginx
    container_name: nginx
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/log:/var/log/nginx
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      - web
volumes:
  postgres_data:
